sqlplus /nolog @crtab 1 &
sqlplus /nolog @crtab 2 &
sqlplus /nolog @crtab 3 &
sqlplus /nolog @crtab 4 &
sqlplus /nolog @crtab 5 &
sqlplus /nolog @crtab 6 &
sqlplus /nolog @crtab 7 &
sqlplus /nolog @crtab 8 &
sqlplus /nolog @crtab 9 &
sqlplus /nolog @crtab 10 &
sqlplus /nolog @crtab 11 &
sqlplus /nolog @crtab 12 &
sqlplus /nolog @crtab 13 &
sqlplus /nolog @crtab 14 &
sqlplus /nolog @crtab 15 &
sqlplus /nolog @crtab 16 &
sqlplus /nolog @crtab 17 &
sqlplus /nolog @crtab 18 &
sqlplus /nolog @crtab 19 &
sqlplus /nolog @crtab 20 &
sqlplus /nolog @crtab 21 &
sqlplus /nolog @crtab 22 &
sqlplus /nolog @crtab 23 &
sqlplus /nolog @crtab 24 &
sqlplus /nolog @crtab 25 &
sqlplus /nolog @crtab 26 &
sqlplus /nolog @crtab 27 &
sqlplus /nolog @crtab 28 &
sqlplus /nolog @crtab 29 &
sqlplus /nolog @crtab 30 &
sqlplus /nolog @crtab 31 &
sqlplus /nolog @crtab 32 &
sqlplus /nolog @crtab 33 &
sqlplus /nolog @crtab 34 &
sqlplus /nolog @crtab 35 &
sqlplus /nolog @crtab 36 &
sqlplus /nolog @crtab 37 &
sqlplus /nolog @crtab 38 &
sqlplus /nolog @crtab 39 &
sqlplus /nolog @crtab 40 &
sqlplus /nolog @crtab 41 &
sqlplus /nolog @crtab 42 &
sqlplus /nolog @crtab 43 &
sqlplus /nolog @crtab 44 &
sqlplus /nolog @crtab 45 &
sqlplus /nolog @crtab 46 &
sqlplus /nolog @crtab 47 &
sqlplus /nolog @crtab 48 &
sqlplus /nolog @crtab 49 &
sqlplus /nolog @crtab 50 &
sqlplus /nolog @crtab 51 &
sqlplus /nolog @crtab 52 &
sqlplus /nolog @crtab 53 &
sqlplus /nolog @crtab 54 &
sqlplus /nolog @crtab 55 &
sqlplus /nolog @crtab 56 &
sqlplus /nolog @crtab 57 &
sqlplus /nolog @crtab 58 &
sqlplus /nolog @crtab 59 &
sqlplus /nolog @crtab 60 &
sqlplus /nolog @crtab 61 &
sqlplus /nolog @crtab 62 &
sqlplus /nolog @crtab 63 &
sqlplus /nolog @crtab 64 &
sqlplus /nolog @crtab 65 &
sqlplus /nolog @crtab 66 &
sqlplus /nolog @crtab 67 &
sqlplus /nolog @crtab 68 &
sqlplus /nolog @crtab 69 &
sqlplus /nolog @crtab 70 &
sqlplus /nolog @crtab 71 &
sqlplus /nolog @crtab 72 &
sqlplus /nolog @crtab 73 &
sqlplus /nolog @crtab 74 &
sqlplus /nolog @crtab 75 &
sqlplus /nolog @crtab 76 &
sqlplus /nolog @crtab 77 &
sqlplus /nolog @crtab 78 &
sqlplus /nolog @crtab 79 &
sqlplus /nolog @crtab 80 &
sqlplus /nolog @crtab 81 &
sqlplus /nolog @crtab 82 &
sqlplus /nolog @crtab 83 &
sqlplus /nolog @crtab 84 &
sqlplus /nolog @crtab 85 &
sqlplus /nolog @crtab 86 &
sqlplus /nolog @crtab 87 &
sqlplus /nolog @crtab 88 &
sqlplus /nolog @crtab 89 &
sqlplus /nolog @crtab 90 &
sqlplus /nolog @crtab 91 &
sqlplus /nolog @crtab 92 &
sqlplus /nolog @crtab 93 &
sqlplus /nolog @crtab 94 &
sqlplus /nolog @crtab 95 &
sqlplus /nolog @crtab 96 &
sqlplus /nolog @crtab 97 &
sqlplus /nolog @crtab 98 &
sqlplus /nolog @crtab 99 &
sqlplus /nolog @crtab 100 &
